theme: jekyll-theme-hacker
title: "GitHub Lowlands Community Blog"
description: "A blog for the GitHub Lowlands Community"
author:
  name: "GitHub Lowlands Community"
  email: "contact@githublowlandscommunity.com"
